// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfbncwsbgunpkdwmpqhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmYm5jd3NiZ3VucGtkd21wcWhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NTQ4NjUsImV4cCI6MjA1ODAzMDg2NX0.ZRmr-L8R4EiEtSmfA69ynq_X9IEra72llU4l2OO5djU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);